![alt text](https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png)

In [5]:
!pip install jovian --upgrade

     |████████████████████████████████| 83 kB 62 kB/s  eta 0:00:01
  Created wheel for uuid: filename=uuid-1.30-py3-none-any.whl size=6500 sha256=7fc44581f40b8edbc6d45bbfe6a6f66b7054f91f366a9abda3319cdf208cd7d0
  Stored in directory: /home/rajat/.cache/pip/wheels/2a/ea/87/dd57f1ecb4f0752f3e1dbf958ebf8b36d920d190425bcdc24d
Successfully built uuid


In [ ]:
import torch

In [7]:
import jovian
import torch
import numpy as np
import pandas as pd


<IPython.core.display.Javascript object>

In [0]:
#matrix
T1 = torch.tensor([[1.,2.,3.],
                       [3.4,5.6,2.4]])

In [20]:
T1

tensor([[1.0000, 2.0000, 3.0000],
        [3.4000, 5.6000, 2.4000]])

In [21]:
T1.shape

torch.Size([2, 3])

In [22]:
#vector
T2 =torch.tensor([1,3,4,23])
T2

tensor([ 1,  3,  4, 23])

In [23]:
T2.shape

torch.Size([4])

In [0]:
#3d array
T3  = torch.tensor([[[1.2,2.3,3.4],
                     [12,4.4,4.4]],
                    [[1.3,43.4,54.3],
                     [1.4,6.7,5.7]]])

In [28]:
T3.shape
# 2 row 2 colmns 3 elaments in each

torch.Size([2, 2, 3])

# Tensor Operations
---------------------

In [0]:
# linear inequality with torch
x = torch.tensor(10.)
w=torch.tensor(1.1 , requires_grad=True) # requires_grad is to enable gradient (partial differentation). grad stored in grad object
b = torch.tensor(2.4,requires_grad=True)

In [0]:
y = w*x+b

In [32]:
print(y)

tensor(13.4000, grad_fn=<AddBackward0>)


In [0]:
y.backward()# doing partial differentation

In [34]:
print("dy/dx",x.grad)# print none becoz we have not set  requires_grid to true for this
print("dy/dw", w.grad)
print("dy/db", b.grad)

dy/dx None
dy/dw tensor(10.)
dy/db tensor(1.)


In [36]:
T3.dtype

torch.float32

In [0]:
N = np.arange(1,10)

In [38]:
N

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
N  = np.array([[1.2,3.4],[3.4,4.5]])

In [44]:
N

array([[1.2, 3.4],
       [3.4, 4.5]])

In [45]:
N.shape

(2, 2)

In [46]:
N.dtype

dtype('float64')

In [48]:
# converting tensor to numpy
z = y.numpy()
# see the error it's very useful

RuntimeError: ignored

In [0]:
M = T3.numpy()
# surprise it is converted becoz its not having gradient enable

In [54]:
M

array([[[ 1.2,  2.3,  3.4],
        [12. ,  4.4,  4.4]],

       [[ 1.3, 43.4, 54.3],
        [ 1.4,  6.7,  5.7]]], dtype=float32)

In [57]:
L = w.numpy()
# see the diff here

RuntimeError: ignored

In [0]:
# correct method to convert those tensors which have gradient
z = y.detach().numpy()

In [50]:
z

array(13.4, dtype=float32)

In [0]:
# converting to tensor from numpy array
T4 = torch.from_numpy(z)

In [52]:
T4

tensor(13.4000)

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
