![alt text](https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png)

In [3]:
!pip install jovian



In [9]:
!pip3 install torch==1.2.0+cu92 torchvision==0.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html


Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 663.1MB 24kB/s 
     |████████████████████████████████| 8.8MB 33.3MB/s 
  Found existing installation: torch 1.5.0+cu101
    Uninstalling torch-1.5.0+cu101:
      Successfully uninstalled torch-1.5.0+cu101
  Found existing installation: torchvision 0.6.0+cu101
    Uninstalling torchvision-0.6.0+cu101:
      Successfully uninstalled torchvision-0.6.0+cu101


In [0]:
import jovian
import torch
import numpy as np
import pandas as pd


In [0]:
#matrix
T1 = torch.tensor([[1.,2.,3.],
                       [3.4,5.6,2.4]])

In [20]:
T1

tensor([[1.0000, 2.0000, 3.0000],
        [3.4000, 5.6000, 2.4000]])

In [21]:
T1.shape

torch.Size([2, 3])

In [22]:
#vector
T2 =torch.tensor([1,3,4,23])
T2

tensor([ 1,  3,  4, 23])

In [23]:
T2.shape

torch.Size([4])

In [0]:
#3d array
T3  = torch.tensor([[[1.2,2.3,3.4],
                     [12,4.4,4.4]],
                    [[1.3,43.4,54.3],
                     [1.4,6.7,5.7]]])

In [28]:
T3.shape
# 2 row 2 colmns 3 elaments in each

torch.Size([2, 2, 3])

# Tensor Operations
---------------------

In [0]:
# linear inequality with torch
x = torch.tensor(10.)
w=torch.tensor(1.1 , requires_grad=True) # requires_grad is to enable gradient (partial differentation). grad stored in grad object
b = torch.tensor(2.4,requires_grad=True)

In [0]:
y = w*x+b

In [32]:
print(y)

tensor(13.4000, grad_fn=<AddBackward0>)


In [0]:
y.backward()# doing partial differentation

In [34]:
print("dy/dx",x.grad)# print none becoz we have not set  requires_grid to true for this
print("dy/dw", w.grad)
print("dy/db", b.grad)

dy/dx None
dy/dw tensor(10.)
dy/db tensor(1.)


In [36]:
T3.dtype

torch.float32

In [0]:
N = np.arange(1,10)

In [38]:
N

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
N  = np.array([[1.2,3.4],[3.4,4.5]])

In [44]:
N

array([[1.2, 3.4],
       [3.4, 4.5]])

In [45]:
N.shape

(2, 2)

In [46]:
N.dtype

dtype('float64')

In [48]:
# converting tensor to numpy
z = y.numpy()
# see the error it's very useful

RuntimeError: ignored

In [0]:
M = T3.numpy()
# surprise it is converted becoz its not having gradient enable

In [54]:
M

array([[[ 1.2,  2.3,  3.4],
        [12. ,  4.4,  4.4]],

       [[ 1.3, 43.4, 54.3],
        [ 1.4,  6.7,  5.7]]], dtype=float32)

In [57]:
L = w.numpy()
# see the diff here

RuntimeError: ignored

In [0]:
# correct method to convert those tensors which have gradient
z = y.detach().numpy()

In [50]:
z

array(13.4, dtype=float32)

In [0]:
# converting to tensor from numpy array
T4 = torch.from_numpy(z)

In [52]:
T4

tensor(13.4000)

In [58]:
jovian.commit()

[jovian] Error: Failed to detect Jupyter notebook or Python script. Skipping..
